### PR TITLE
refactor: removing and simplifying imports 

### LINKED ISSUE #94: Duplicate imports
Nitpicking, but there are duplicate package imports for purrr https://github.com/tidyfun/tf/blob/dev/R/tfd-class.R#L1 and https://github.com/tidyfun/tf/blob/dev/R/tfd-class.R#L1 while also import the functions https://github.com/tidyfun/tf/blob/dev/R/fwise.R#L17and using it with the explicit namespace: https://github.com/tidyfun/tf/blob/dev/R/fwise.R#L51 the same is true for the mgcv and stats imports.

Suggestion would be to move the whole package imports (i.e. `@import purrr` to the R/tf-package.R file like done in dplyr or other many other packages: https://github.com/tidyverse/dplyr/blob/main/R/dplyr.R#L6

### PR DESCRIPTION
**Pull request by m-muecke**
Closes: https://github.com/tidyfun/tf/issues/94

### CODE REVIEW

**Comment by fabian-s** [comment]
thanks -- 

- did you do this manually or use some kind of script to find the relevant LOCs? if the latter, could you post it here?
- why `zoo::bla` for some functions and `importFrom zoo blub` for others?

**Comment by m-muecke** [comment]
> thanks --
> 
> * did you do this manually or use some kind of script to find the relevant LOCs? if the latter, could you post it here?
> * why `zoo::bla` for some functions and `importFrom zoo blub` for others?

1. no script, I just greping in vim
2. I wanted to use namespace prefix for zoo functions, but due to the `get()` call @importFrom zoo rollmean rollmedian was needed for having them in the namespace. If you like I can import the other zoo functions, I just didn't want the entire zoo package imported like before

**Comment by fabian-s** [comment]
> If you like I can import the other zoo functions, I just didn't want the entire zoo package imported like before

I would prefer that, for consistency

**Comment by m-muecke** [comment]
> > If you like I can import the other zoo functions, I just didn't want the entire zoo package imported like before
> 
> I would prefer that, for consistency

done

**Pull request merged**
