### PR TITLE
tests: add test for conversions and constructor

### PR DESCRIPTION
**Pull request by m-muecke**
- This covers simple cases for regular and irregular tf vectors for both unnesting and not unnesting
- Use `deparse1()`

### CODE REVIEW

**Comment by m-muecke** [comment]
@fabian-s 

I'm not sure what the expected behaviour you want here, when calling `tfd` with `NULL` and `NA`s that are not of type `numeric` or `integer`, both cases don't fail but give this message and I guess fall back to some vctrs constuctor:

``` r
tf::tfd(NA)
#> input `data` not recognized class; returning prototype of length 0
#> tfd[0] on (0,0) based on 0 evaluations each
#> interpolation by tf_approx_linear
tf::tfd(NULL)
#> input `data` not recognized class; returning prototype of length 0
#> tfd[0] on (0,0) based on 0 evaluations each
#> interpolation by tf_approx_linear
```

<sup>Created on 2024-07-31 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by fabian-s** [comment]
thanks -- 

"returning prototype of length 0" for unsuitable inputs is what `vctrs::vec_ptype` does
this is useful for numeric inputs  (& necessary so vctrs stuff works properly, IIRC).

re expected behavior for NA_character or NULL:

not actually sure about the pros&cons of throwing an error for non-numeric inputs instead, right now `tfd.default` basically creates a zero-length prototype vector for any input the other tfd-methods can't handle. probably not the safest or most consistent way to handle this... better ideas?

**Comment by m-muecke** [comment]
> thanks --
> 
> "returning prototype of length 0" for unsuitable inputs is what `vctrs::vec_ptype` does this is useful for numeric inputs (& necessary so vctrs stuff works properly, IIRC).
> 
> re expected behavior for NA_character or NULL:
> 
> not actually sure about the pros&cons of throwing an error for non-numeric inputs instead, right now `tfd.default` basically creates a zero-length prototype vector for any input the other tfd-methods can't handle. probably not the safest or most consistent way to handle this... better ideas?

Then I just overlooked the default implementation thats already in-place. Tbh I don't have the strongest opinion on this, but for calling `tf::tfd()` with no args I wouldn't throw a message and just return the empty vector like it already does or just throw an error. For non-numeric I would just throw an error since numeric is required for the vectors and the NULL case I would probably also throw an error, but package handle this differently, see for reference:

``` r
# blob package
blob::blob()
#> <blob[0]>
blob::blob(NULL)
#> <blob[1]>
#> [1] <NA>
blob::blob(NA)
#> Error: `x` must be a list of raw vectors

# pillar package
pillar::num()
#> Error in pillar::num(): argument "x" is missing, with no default
pillar::num(NULL)
#> Error in pillar::num(NULL): is.numeric(x) is not TRUE
pillar::num("")
#> Error in pillar::num(""): is.numeric(x) is not TRUE
pillar::num(NA)
#> Error in pillar::num(NA): is.numeric(x) is not TRUE

# haven package
haven::labelled()
#> <labelled<double>[0]>
haven::labelled(NULL)
#> Error in `vec_data()`:
#> ! `x` must be a vector, not `NULL`.
haven::labelled(NA)
#> Error in `new_labelled()`:
#> ! `x` must be a numeric or a character vector.

# hms package
hms::hms()
#> hms()
hms::hms(NULL)
#> hms()
hms::hms("")
#> Error: All arguments must be numeric or NA
hms::hms(NA)
#> NA
```

<sup>Created on 2024-07-31 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Then I think you can merge the tests and we can always open an issue for the handling of the edge cases.

**Comment by fabian-s** [comment]
thanks a lot for this. 
are you still working on it or should I merge now?

**Comment by m-muecke** [comment]
> thanks a lot for this. are you still working on it or should I merge now?

let me just add one or two more tests for the `as.matrix.tf` while I'm at it to finish the tests for the converters

**Comment by fabian-s** [comment]
ty sm!

**Pull request merged**
